#!perl

sub on_user_command
{
	my($self,$cmd) = @_;

	if( $cmd eq "font:increase" ) {
		font_change_size( $self,  5);
	} elsif ($cmd eq "font:decrease") {
		font_change_size( $self,  -5);
	}
}

sub font_change_size
{
	my($term, $change) = @_;

	my ($fontstring) = $term->resource('font');

	#-xos4-terminus-medium-r-normal-*-12-*-*-*-*-*-*-1

	$term->scr_add_lines("\rDEBUG: my font is $fontstring\n");

	my @fields = qw( foundry family weight slant setwidth style pixelSize pointSize Xresolution Yresolution spacing averageWidth registry encoding );

	my %font;

	$fontstring =~ s/^-//;  # Strip leading - before split
	@font{@fields} = split(/-/,$fontstring);

	# This sucks.  Should use
	#  xlsfonts -fn '-xos4-terminus-medium-r-normal-*-*-*-72-72-c-*-iso8859-1'
	# and pick the next/prev one.  However, if we don't know the display
	# pitch and the locale, we're kinda hosed.
	$font{pixelSize} += $change;
	if( $font{pixelSize} < 5 ) {
		$font{pixelSize} = 5;
	}

	my $newname = '-' . join('-', @font{@fields});

	# And change the font
	$term->cmd_parse( "\033]710;$newname\007");
}
